
server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myweb?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 700524
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  typeAliasesPackage: com.example.demosecond.dao.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true